//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaMercadorias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCADORIA
    {
        public int ID { get; set; }
        public Nullable<int> TipoID { get; set; }
        public Nullable<int> NegocioID { get; set; }
        public string NOME { get; set; }
        public Nullable<int> QUANTIDADE { get; set; }
        public Nullable<decimal> PRECO { get; set; }
    
        public virtual TIPO_NEGOCIO TIPO_NEGOCIO { get; set; }
        public virtual TIPO_MERCADORIA TIPO_MERCADORIA { get; set; }
    }
}
