//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaMercadorias.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadesLojaMercadoriasBD : DbContext
    {
        public EntidadesLojaMercadoriasBD()
            : base("name=EntidadesLojaMercadoriasBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MERCADORIA> MERCADORIA { get; set; }
        public DbSet<TIPO_MERCADORIA> TIPO_MERCADORIA { get; set; }
        public DbSet<TIPO_NEGOCIO> TIPO_NEGOCIO { get; set; }
    }
}
